-- SYNTAX TEST "Packages/Dhall/dhall.sublime-syntax"

[ Natural/fold
--^^^^^^^^^^^^ support.function.dhall
, Natural/build
--^^^^^^^^^^^^^ support.function.dhall
, Natural/isZero
--^^^^^^^^^^^^^^ support.function.dhall
, Natural/even
--^^^^^^^^^^^^ support.function.dhall
, Natural/odd
--^^^^^^^^^^^ support.function.dhall
, Natural/toInteger
--^^^^^^^^^^^^^^^^^ support.function.dhall
, Natural/show
--^^^^^^^^^^^^ support.function.dhall
, Integer/toDouble
--^^^^^^^^^^^^^^^^ support.function.dhall
, Integer/show
--^^^^^^^^^^^^ support.function.dhall
, Integer/negate
--^^^^^^^^^^^^^^ support.function.dhall
, Integer/clamp
--^^^^^^^^^^^^^ support.function.dhall
, Natural/subtract
--^^^^^^^^^^^^^^^^ support.function.dhall
, Double/show
--^^^^^^^^^^^ support.function.dhall
, List/build
--^^^^^^^^^^ support.function.dhall
, List/fold
--^^^^^^^^^ support.function.dhall
, List/length
--^^^^^^^^^^^ support.function.dhall
, List/head
--^^^^^^^^^ support.function.dhall
, List/last
--^^^^^^^^^ support.function.dhall
, List/indexed
--^^^^^^^^^^^^ support.function.dhall
, List/reverse
--^^^^^^^^^^^^ support.function.dhall
, Text/show
--^^^^^^^^^ support.function.dhall
, Text/replace
--^^^^^^^^^^^^ support.function.dhall
, Date/show
--^^^^^^^^^ support.function.dhall
, Time/show
--^^^^^^^^^ support.function.dhall
, TimeZone/show
--^^^^^^^^^^^^^ support.function.dhall
, Bool
--^^^^ storage.type.dhall
, True
--^^^^ constant.language.dhall
, False
--^^^^^ constant.language.dhall
, Optional
--^^^^^^^^ storage.type.dhall
, None
--^^^^ constant.language.dhall
, Natural
--^^^^^^^ storage.type.dhall
, Integer
--^^^^^^^ storage.type.dhall
, Double
--^^^^^^ storage.type.dhall
, Text
--^^^^ storage.type.dhall
, Bytes
--^^^^^ storage.type.dhall
, List
--^^^^ storage.type.dhall
, Date
--^^^^ storage.type.dhall
, Time
--^^^^ storage.type.dhall
, TimeZone
--^^^^^^^^ storage.type.dhall
, Type
--^^^^ storage.type.dhall
, Kind
--^^^^ storage.type.dhall
, Sort
--^^^^ storage.type.dhall
]
